In [27]:
import pandas as pd

raw_train_calc_df = pd.read_csv("../data_description/calc_case_description_train_set.csv")
raw_train_mass_df = pd.read_csv("../data_description/mass_case_description_train_set.csv")

raw_test_calc_df = pd.read_csv("../data_description/calc_case_description_test_set.csv")
raw_test_mass_df = pd.read_csv("../data_description/mass_case_description_test_set.csv")

raw_df = pd.concat([raw_train_calc_df, raw_train_mass_df, raw_test_calc_df, raw_test_mass_df], ignore_index=True)

raw_df.head()

,patient_id,breast density,left or right breast,image view,abnormality id,abnormality type,calc type,calc distribution,assessment,pathology,subtlety,image file path,cropped image file path,ROI mask file path,breast_density,mass shape,mass margins
0,P_00005,3.0,RIGHT,CC,1,calcification,AMORPHOUS,CLUSTERED,3,MALIGNANT,3,Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.408909860712120272633130274602115723157/1.3.6.1.4.1.9590.100.1.2.47414316010368386519740343172775938548/000000.dcm,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.328778919012412769218080124214088709081/1.3.6.1.4.1.9590.100.1.2.393344010211719049419601138200355094682/000001.dcm\n,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.328778919012412769218080124214088709081/1.3.6.1.4.1.9590.100.1.2.393344010211719049419601138200355094682/000000.dcm,NaN,NaN,NaN
1,P_00005,3.0,RIGHT,MLO,1,calcification,AMORPHOUS,CLUSTERED,3,MALIGNANT,3,Calc-Training_P_00005_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.427517897311902339923511678883689433338/1.3.6.1.4.1.9590.100.1.2.250596608311207922527805669693579696727/000000.dcm,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.67512362210319636108148504382680781938/1.3.6.1.4.1.9590.100.1.2.296281207812130400303493285473798422894/000001.dcm\n,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.67512362210319636108148504382680781938/1.3.6.1.4.1.9590.100.1.2.296281207812130400303493285473798422894/000000.dcm,NaN,NaN,NaN
2,P_00007,4.0,LEFT,CC,1,calcification,PLEOMORPHIC,LINEAR,4,BENIGN,4,Calc-Training_P_00007_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.201322325113694962619881476352450072222/1.3.6.1.4.1.9590.100.1.2.228699627313487111012474405462022068297/000000.dcm,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.241202057913673145232234613012384759880/1.3.6.1.4.1.9590.100.1.2.314135871111943890422150247820137952041/000001.dcm\n,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.241202057913673145232234613012384759880/1.3.6.1.4.1.9590.100.1.2.314135871111943890422150247820137952041/000000.dcm,NaN,NaN,NaN
3,P_00007,4.0,LEFT,MLO,1,calcification,PLEOMORPHIC,LINEAR,4,BENIGN,4,Calc-Training_P_00007_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.370479499712916693322010643793108454887/1.3.6.1.4.1.9590.100.1.2.104743410411133110629448544090466900446/000000.dcm,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.314250272911170289203882349024229868823/1.3.6.1.4.1.9590.100.1.2.91458279612485515203413781822560852485/000001.dcm\n,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.314250272911170289203882349024229868823/1.3.6.1.4.1.9590.100.1.2.91458279612485515203413781822560852485/000000.dcm,NaN,NaN,NaN
4,P_00008,1.0,LEFT,CC,1,calcification,NaN,REGIONAL,2,BENIGN_WITHOUT_CALLBACK,3,Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/000000.dcm,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.336811694512764490002272925921108351157/1.3.6.1.4.1.9590.100.1.2.281397494612871934937455783843630775495/000001.dcm\n,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.336811694512764490002272925921108351157/1.3.6.1.4.1.9590.100.1.2.281397494612871934937455783843630775495/000000.dcm,NaN,NaN,NaN

In [28]:
raw_df = raw_df[['patient_id', 'pathology', 'image file path', 'cropped image file path', 'ROI mask file path']]

In [29]:
raw_df.head()

,patient_id,pathology,image file path,cropped image file path,ROI mask file path
0,P_00005,MALIGNANT,Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.408909860712120272633130274602115723157/1.3.6.1.4.1.9590.100.1.2.47414316010368386519740343172775938548/000000.dcm,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.328778919012412769218080124214088709081/1.3.6.1.4.1.9590.100.1.2.393344010211719049419601138200355094682/000001.dcm\n,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.328778919012412769218080124214088709081/1.3.6.1.4.1.9590.100.1.2.393344010211719049419601138200355094682/000000.dcm
1,P_00005,MALIGNANT,Calc-Training_P_00005_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.427517897311902339923511678883689433338/1.3.6.1.4.1.9590.100.1.2.250596608311207922527805669693579696727/000000.dcm,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.67512362210319636108148504382680781938/1.3.6.1.4.1.9590.100.1.2.296281207812130400303493285473798422894/000001.dcm\n,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.67512362210319636108148504382680781938/1.3.6.1.4.1.9590.100.1.2.296281207812130400303493285473798422894/000000.dcm
2,P_00007,BENIGN,Calc-Training_P_00007_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.201322325113694962619881476352450072222/1.3.6.1.4.1.9590.100.1.2.228699627313487111012474405462022068297/000000.dcm,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.241202057913673145232234613012384759880/1.3.6.1.4.1.9590.100.1.2.314135871111943890422150247820137952041/000001.dcm\n,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.241202057913673145232234613012384759880/1.3.6.1.4.1.9590.100.1.2.314135871111943890422150247820137952041/000000.dcm
3,P_00007,BENIGN,Calc-Training_P_00007_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.370479499712916693322010643793108454887/1.3.6.1.4.1.9590.100.1.2.104743410411133110629448544090466900446/000000.dcm,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.314250272911170289203882349024229868823/1.3.6.1.4.1.9590.100.1.2.91458279612485515203413781822560852485/000001.dcm\n,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.314250272911170289203882349024229868823/1.3.6.1.4.1.9590.100.1.2.91458279612485515203413781822560852485/000000.dcm
4,P_00008,BENIGN_WITHOUT_CALLBACK,Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/000000.dcm,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.336811694512764490002272925921108351157/1.3.6.1.4.1.9590.100.1.2.281397494612871934937455783843630775495/000001.dcm\n,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.336811694512764490002272925921108351157/1.3.6.1.4.1.9590.100.1.2.281397494612871934937455783843630775495/000000.dcm

In [30]:
raw_df['pathology'].value_counts()

pathology
MALIGNANT                  1457
BENIGN                     1429
BENIGN_WITHOUT_CALLBACK     682
Name: count, dtype: int64

In [31]:
raw_df['pathology'] = raw_df['pathology'].map({'BENIGN': 0, 'MALIGNANT': 1, 'BENIGN_WITHOUT_CALLBACK': 0})

raw_df.head()

,patient_id,pathology,image file path,cropped image file path,ROI mask file path
0,P_00005,1,Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.408909860712120272633130274602115723157/1.3.6.1.4.1.9590.100.1.2.47414316010368386519740343172775938548/000000.dcm,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.328778919012412769218080124214088709081/1.3.6.1.4.1.9590.100.1.2.393344010211719049419601138200355094682/000001.dcm\n,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.328778919012412769218080124214088709081/1.3.6.1.4.1.9590.100.1.2.393344010211719049419601138200355094682/000000.dcm
1,P_00005,1,Calc-Training_P_00005_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.427517897311902339923511678883689433338/1.3.6.1.4.1.9590.100.1.2.250596608311207922527805669693579696727/000000.dcm,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.67512362210319636108148504382680781938/1.3.6.1.4.1.9590.100.1.2.296281207812130400303493285473798422894/000001.dcm\n,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.67512362210319636108148504382680781938/1.3.6.1.4.1.9590.100.1.2.296281207812130400303493285473798422894/000000.dcm
2,P_00007,0,Calc-Training_P_00007_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.201322325113694962619881476352450072222/1.3.6.1.4.1.9590.100.1.2.228699627313487111012474405462022068297/000000.dcm,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.241202057913673145232234613012384759880/1.3.6.1.4.1.9590.100.1.2.314135871111943890422150247820137952041/000001.dcm\n,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.241202057913673145232234613012384759880/1.3.6.1.4.1.9590.100.1.2.314135871111943890422150247820137952041/000000.dcm
3,P_00007,0,Calc-Training_P_00007_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.370479499712916693322010643793108454887/1.3.6.1.4.1.9590.100.1.2.104743410411133110629448544090466900446/000000.dcm,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.314250272911170289203882349024229868823/1.3.6.1.4.1.9590.100.1.2.91458279612485515203413781822560852485/000001.dcm\n,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.314250272911170289203882349024229868823/1.3.6.1.4.1.9590.100.1.2.91458279612485515203413781822560852485/000000.dcm
4,P_00008,0,Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/000000.dcm,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.336811694512764490002272925921108351157/1.3.6.1.4.1.9590.100.1.2.281397494612871934937455783843630775495/000001.dcm\n,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.336811694512764490002272925921108351157/1.3.6.1.4.1.9590.100.1.2.281397494612871934937455783843630775495/000000.dcm

In [32]:
target_columns = ['image file path', 'cropped image file path', 'ROI mask file path']


unique_vals = {col: raw_df[col].drop_duplicates().reset_index(drop=True) for col in target_columns}
for col, s in unique_vals.items():
    print(col, s.duplicated().sum())  # will all be 0

for col in target_columns:
    deduped = raw_df[col].drop_duplicates()
    print(col, "len:", len(deduped), "unique:", deduped.nunique(), "duplicated after dedup:", deduped.duplicated().sum())

image file path 0
cropped image file path 0
ROI mask file path 0
image file path len: 3103 unique: 3103 duplicated after dedup: 0
cropped image file path len: 3568 unique: 3568 duplicated after dedup: 0
ROI mask file path len: 3568 unique: 3568 duplicated after dedup: 0

In [33]:
raw_df.isnull().sum()

patient_id                 0
pathology                  0
image file path            0
cropped image file path    0
ROI mask file path         0
dtype: int64

In [34]:
pd.set_option("display.max_colwidth", None)

In [35]:
raw_df['image file path'].head(10)

0      Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.408909860712120272633130274602115723157/1.3.6.1.4.1.9590.100.1.2.47414316010368386519740343172775938548/000000.dcm
1    Calc-Training_P_00005_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.427517897311902339923511678883689433338/1.3.6.1.4.1.9590.100.1.2.250596608311207922527805669693579696727/000000.dcm
2      Calc-Training_P_00007_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.201322325113694962619881476352450072222/1.3.6.1.4.1.9590.100.1.2.228699627313487111012474405462022068297/000000.dcm
3     Calc-Training_P_00007_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.370479499712916693322010643793108454887/1.3.6.1.4.1.9590.100.1.2.104743410411133110629448544090466900446/000000.dcm
4      Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/000000.dcm
5      Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/000000.dcm
6      Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/000000.dcm
7       Calc-Training_P_00008_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.84155842712765660429462608981255328663/1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907/000000.dcm
8       Calc-Training_P_00008_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.84155842712765660429462608981255328663/1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907/000000.dcm
9       Calc-Training_P_00008_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.84155842712765660429462608981255328663/1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907/000000.dcm
Name: image file path, dtype: str

In [36]:
raw_df['image file path'] = raw_df['image file path'].str[:-10]

raw_df['image file path'].head(10)

0      Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.408909860712120272633130274602115723157/1.3.6.1.4.1.9590.100.1.2.47414316010368386519740343172775938548/
1    Calc-Training_P_00005_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.427517897311902339923511678883689433338/1.3.6.1.4.1.9590.100.1.2.250596608311207922527805669693579696727/
2      Calc-Training_P_00007_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.201322325113694962619881476352450072222/1.3.6.1.4.1.9590.100.1.2.228699627313487111012474405462022068297/
3     Calc-Training_P_00007_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.370479499712916693322010643793108454887/1.3.6.1.4.1.9590.100.1.2.104743410411133110629448544090466900446/
4      Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/
5      Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/
6      Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/
7       Calc-Training_P_00008_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.84155842712765660429462608981255328663/1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907/
8       Calc-Training_P_00008_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.84155842712765660429462608981255328663/1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907/
9       Calc-Training_P_00008_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.84155842712765660429462608981255328663/1.3.6.1.4.1.9590.100.1.2.14784689311239808604822345534163797907/
Name: image file path, dtype: str

In [37]:
raw_df['cropped image file path'].head(10)

0    Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.328778919012412769218080124214088709081/1.3.6.1.4.1.9590.100.1.2.393344010211719049419601138200355094682/000001.dcm\n
1    Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.67512362210319636108148504382680781938/1.3.6.1.4.1.9590.100.1.2.296281207812130400303493285473798422894/000001.dcm\n
2     Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.241202057913673145232234613012384759880/1.3.6.1.4.1.9590.100.1.2.314135871111943890422150247820137952041/000001.dcm\n
3     Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.314250272911170289203882349024229868823/1.3.6.1.4.1.9590.100.1.2.91458279612485515203413781822560852485/000001.dcm\n
4     Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.336811694512764490002272925921108351157/1.3.6.1.4.1.9590.100.1.2.281397494612871934937455783843630775495/000001.dcm\n
5       Calc-Training_P_00008_LEFT_CC_2/1.3.6.1.4.1.9590.100.1.2.207558519313356140106496367610041842177/1.3.6.1.4.1.9590.100.1.2.2024181113538627406890441552979568519/000001.dcm\n
6      Calc-Training_P_00008_LEFT_CC_3/1.3.6.1.4.1.9590.100.1.2.74480335312443720440103727953726257477/1.3.6.1.4.1.9590.100.1.2.358964325411863896506852883280957478483/000001.dcm\n
7     Calc-Training_P_00008_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.194216643012943010222741170453094926786/1.3.6.1.4.1.9590.100.1.2.81216723513826953322779836314123146864/000001.dcm\n
8    Calc-Training_P_00008_LEFT_MLO_2/1.3.6.1.4.1.9590.100.1.2.363735588611036329226111671323507141479/1.3.6.1.4.1.9590.100.1.2.101644730412034535338273957660005319377/000001.dcm\n
9      Calc-Training_P_00008_LEFT_MLO_3/1.3.6.1.4.1.9590.100.1.2.161386321913969368010907593284201308852/1.3.6.1.4.1.9590.100.1.2.4165882011639284134385639942174899929/000001.dcm\n
Name: cropped image file path, dtype: str

In [38]:
raw_df['cropped image file path'] = raw_df['cropped image file path'].str[:-11]
raw_df['cropped image file path'].head(10)

0    Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.328778919012412769218080124214088709081/1.3.6.1.4.1.9590.100.1.2.393344010211719049419601138200355094682/
1    Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.67512362210319636108148504382680781938/1.3.6.1.4.1.9590.100.1.2.296281207812130400303493285473798422894/
2     Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.241202057913673145232234613012384759880/1.3.6.1.4.1.9590.100.1.2.314135871111943890422150247820137952041/
3     Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.314250272911170289203882349024229868823/1.3.6.1.4.1.9590.100.1.2.91458279612485515203413781822560852485/
4     Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.336811694512764490002272925921108351157/1.3.6.1.4.1.9590.100.1.2.281397494612871934937455783843630775495/
5       Calc-Training_P_00008_LEFT_CC_2/1.3.6.1.4.1.9590.100.1.2.207558519313356140106496367610041842177/1.3.6.1.4.1.9590.100.1.2.2024181113538627406890441552979568519/
6      Calc-Training_P_00008_LEFT_CC_3/1.3.6.1.4.1.9590.100.1.2.74480335312443720440103727953726257477/1.3.6.1.4.1.9590.100.1.2.358964325411863896506852883280957478483/
7     Calc-Training_P_00008_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.194216643012943010222741170453094926786/1.3.6.1.4.1.9590.100.1.2.81216723513826953322779836314123146864/
8    Calc-Training_P_00008_LEFT_MLO_2/1.3.6.1.4.1.9590.100.1.2.363735588611036329226111671323507141479/1.3.6.1.4.1.9590.100.1.2.101644730412034535338273957660005319377/
9      Calc-Training_P_00008_LEFT_MLO_3/1.3.6.1.4.1.9590.100.1.2.161386321913969368010907593284201308852/1.3.6.1.4.1.9590.100.1.2.4165882011639284134385639942174899929/
Name: cropped image file path, dtype: str

In [39]:
raw_df['ROI mask file path'].head(10)

0    Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.328778919012412769218080124214088709081/1.3.6.1.4.1.9590.100.1.2.393344010211719049419601138200355094682/000000.dcm
1    Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.67512362210319636108148504382680781938/1.3.6.1.4.1.9590.100.1.2.296281207812130400303493285473798422894/000000.dcm
2     Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.241202057913673145232234613012384759880/1.3.6.1.4.1.9590.100.1.2.314135871111943890422150247820137952041/000000.dcm
3     Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.314250272911170289203882349024229868823/1.3.6.1.4.1.9590.100.1.2.91458279612485515203413781822560852485/000000.dcm
4     Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.336811694512764490002272925921108351157/1.3.6.1.4.1.9590.100.1.2.281397494612871934937455783843630775495/000000.dcm
5       Calc-Training_P_00008_LEFT_CC_2/1.3.6.1.4.1.9590.100.1.2.207558519313356140106496367610041842177/1.3.6.1.4.1.9590.100.1.2.2024181113538627406890441552979568519/000000.dcm
6      Calc-Training_P_00008_LEFT_CC_3/1.3.6.1.4.1.9590.100.1.2.74480335312443720440103727953726257477/1.3.6.1.4.1.9590.100.1.2.358964325411863896506852883280957478483/000000.dcm
7     Calc-Training_P_00008_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.194216643012943010222741170453094926786/1.3.6.1.4.1.9590.100.1.2.81216723513826953322779836314123146864/000000.dcm
8    Calc-Training_P_00008_LEFT_MLO_2/1.3.6.1.4.1.9590.100.1.2.363735588611036329226111671323507141479/1.3.6.1.4.1.9590.100.1.2.101644730412034535338273957660005319377/000000.dcm
9      Calc-Training_P_00008_LEFT_MLO_3/1.3.6.1.4.1.9590.100.1.2.161386321913969368010907593284201308852/1.3.6.1.4.1.9590.100.1.2.4165882011639284134385639942174899929/000000.dcm
Name: ROI mask file path, dtype: str

In [40]:
raw_df['ROI mask file path'] = raw_df['ROI mask file path'].str[:-10]
raw_df['ROI mask file path'].head(10)

0    Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.328778919012412769218080124214088709081/1.3.6.1.4.1.9590.100.1.2.393344010211719049419601138200355094682/
1    Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.67512362210319636108148504382680781938/1.3.6.1.4.1.9590.100.1.2.296281207812130400303493285473798422894/
2     Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.241202057913673145232234613012384759880/1.3.6.1.4.1.9590.100.1.2.314135871111943890422150247820137952041/
3     Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.314250272911170289203882349024229868823/1.3.6.1.4.1.9590.100.1.2.91458279612485515203413781822560852485/
4     Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.336811694512764490002272925921108351157/1.3.6.1.4.1.9590.100.1.2.281397494612871934937455783843630775495/
5       Calc-Training_P_00008_LEFT_CC_2/1.3.6.1.4.1.9590.100.1.2.207558519313356140106496367610041842177/1.3.6.1.4.1.9590.100.1.2.2024181113538627406890441552979568519/
6      Calc-Training_P_00008_LEFT_CC_3/1.3.6.1.4.1.9590.100.1.2.74480335312443720440103727953726257477/1.3.6.1.4.1.9590.100.1.2.358964325411863896506852883280957478483/
7     Calc-Training_P_00008_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.194216643012943010222741170453094926786/1.3.6.1.4.1.9590.100.1.2.81216723513826953322779836314123146864/
8    Calc-Training_P_00008_LEFT_MLO_2/1.3.6.1.4.1.9590.100.1.2.363735588611036329226111671323507141479/1.3.6.1.4.1.9590.100.1.2.101644730412034535338273957660005319377/
9      Calc-Training_P_00008_LEFT_MLO_3/1.3.6.1.4.1.9590.100.1.2.161386321913969368010907593284201308852/1.3.6.1.4.1.9590.100.1.2.4165882011639284134385639942174899929/
Name: ROI mask file path, dtype: str

In [41]:
raw_df.head()

,patient_id,pathology,image file path,cropped image file path,ROI mask file path
0,P_00005,1,Calc-Training_P_00005_RIGHT_CC/1.3.6.1.4.1.9590.100.1.2.408909860712120272633130274602115723157/1.3.6.1.4.1.9590.100.1.2.47414316010368386519740343172775938548/,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.328778919012412769218080124214088709081/1.3.6.1.4.1.9590.100.1.2.393344010211719049419601138200355094682/,Calc-Training_P_00005_RIGHT_CC_1/1.3.6.1.4.1.9590.100.1.2.328778919012412769218080124214088709081/1.3.6.1.4.1.9590.100.1.2.393344010211719049419601138200355094682/
1,P_00005,1,Calc-Training_P_00005_RIGHT_MLO/1.3.6.1.4.1.9590.100.1.2.427517897311902339923511678883689433338/1.3.6.1.4.1.9590.100.1.2.250596608311207922527805669693579696727/,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.67512362210319636108148504382680781938/1.3.6.1.4.1.9590.100.1.2.296281207812130400303493285473798422894/,Calc-Training_P_00005_RIGHT_MLO_1/1.3.6.1.4.1.9590.100.1.2.67512362210319636108148504382680781938/1.3.6.1.4.1.9590.100.1.2.296281207812130400303493285473798422894/
2,P_00007,0,Calc-Training_P_00007_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.201322325113694962619881476352450072222/1.3.6.1.4.1.9590.100.1.2.228699627313487111012474405462022068297/,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.241202057913673145232234613012384759880/1.3.6.1.4.1.9590.100.1.2.314135871111943890422150247820137952041/,Calc-Training_P_00007_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.241202057913673145232234613012384759880/1.3.6.1.4.1.9590.100.1.2.314135871111943890422150247820137952041/
3,P_00007,0,Calc-Training_P_00007_LEFT_MLO/1.3.6.1.4.1.9590.100.1.2.370479499712916693322010643793108454887/1.3.6.1.4.1.9590.100.1.2.104743410411133110629448544090466900446/,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.314250272911170289203882349024229868823/1.3.6.1.4.1.9590.100.1.2.91458279612485515203413781822560852485/,Calc-Training_P_00007_LEFT_MLO_1/1.3.6.1.4.1.9590.100.1.2.314250272911170289203882349024229868823/1.3.6.1.4.1.9590.100.1.2.91458279612485515203413781822560852485/
4,P_00008,0,Calc-Training_P_00008_LEFT_CC/1.3.6.1.4.1.9590.100.1.2.162256682111885666305889708873412464189/1.3.6.1.4.1.9590.100.1.2.406725628213826290127343763811145520834/,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.336811694512764490002272925921108351157/1.3.6.1.4.1.9590.100.1.2.281397494612871934937455783843630775495/,Calc-Training_P_00008_LEFT_CC_1/1.3.6.1.4.1.9590.100.1.2.336811694512764490002272925921108351157/1.3.6.1.4.1.9590.100.1.2.281397494612871934937455783843630775495/

In [42]:
from sklearn.model_selection import StratifiedGroupKFold

# roughly 80/10/10 → use ~10 folds, take 1 fold as test
sgkf = StratifiedGroupKFold(n_splits=10, shuffle=True, random_state=42)

trainval_idx, test_idx = next(sgkf.split(
    raw_df,
    y=raw_df['pathology'],       # your label column
    groups=raw_df['patient_id']
))

trainval_df = raw_df.iloc[trainval_idx]
test_df     = raw_df.iloc[test_idx]

# repeat on trainval to carve out val (~10% of original ≈ 1/9 of trainval)
sgkf2 = StratifiedGroupKFold(n_splits=9, shuffle=True, random_state=42)

train_idx, val_idx = next(sgkf2.split(
    trainval_df,
    y=trainval_df['pathology'],
    groups=trainval_df['patient_id']
))

train_df = trainval_df.iloc[train_idx]
val_df   = trainval_df.iloc[val_idx]

In [43]:
for name, d in [('train', train_df), ('val', val_df), ('test', test_df)]:
    print(name, len(d))
    print(d['pathology'].value_counts(normalize=True))
    print()

print("original")
print(raw_df['pathology'].value_counts(normalize=True))

train 2854
pathology
0    0.591451
1    0.408549
Name: proportion, dtype: float64

val 356
pathology
0    0.592697
1    0.407303
Name: proportion, dtype: float64

test 358
pathology
0    0.592179
1    0.407821
Name: proportion, dtype: float64

original
pathology
0    0.591648
1    0.408352
Name: proportion, dtype: float64

In [44]:
train_df.to_csv("../dataframes/three_input_train_df.csv", index=False)
test_df.to_csv("../dataframes/three_input_test_df.csv", index=False)
val_df.to_csv("../dataframes/three_input_val_df.csv", index=False)